name: update data.json

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraping script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          python src/scrape.py
      - name: Commit data.json
        run: |
          filename="data.json"
          git config --global user.name "NowScott"
          git config --global user.email "nowscott@qq.com"
          if ! git diff --quiet --exit-code; then
            git add $filename
            git commit -m "Update data.json by GitHub Action"
            git push origin main
          else
            echo "没有变化。"
          fi
