name: Web Scraping and Save as JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run scraping script and save as temp.json
        run: node src/scrape.js > temp.json

      - name: Check previous step result
        id: check_result
        run: echo ::set-output name=result::failure

      - name: Commit data.json (only if previous step succeeded)
        if: steps.check_result.outputs.result != 'failure'
        run: |
          git config --global user.name "NowScott"
          git config --global user.email "nowscott@qq.com"
          git add data.json
          git commit -m "Update data.json"
          git push
