name: Web Scraping and Save as JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

- name: Run scraping script
        run: node src/scrape.js
        id: scrape

      - name: Check if output is error
        id: check-error
        run: echo "::set-output name=is_error::$(grep -q 'error' data.json && echo true || echo false)"

      - name: Commit data.json
        if: steps.check-error.outputs.is_error != 'true'
        run: |
          git config --global user.name "NowScott"
          git config --global user.email "nowscott@qq.com"
          git add data.json
          git commit -m "Update data.json"
          git push
